apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: workshop
data:
  SPRING_PROFILES_ACTIVE: docker
  NEW_RELIC_APP_NAME: workshop-management
  NEW_RELIC_LOG: STDOUT
  NEW_RELIC_APPLICATION_LOGGING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: "true"
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
